version: '3'
services:
  api:
    build: ./api
    expose:
      - '80'
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    restart: always
    command: /start-reload.sh
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  # slack:
  #   image: slack
  #   environment:
  #     SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  #     SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}

volumes:
  db-store:


