version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api/app:/app
    depends_on:
      - db
    restart: always
    command: /start-reload.sh
    ports:
      - 3000:80

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  # slack:
  #   image: slack
  #   environment:
  #     SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  #     SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /sessions

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db-store:
  caddy_data:
    driver: "local"
  images:
    driver: "local"
