version: '3'
services:
  api:
    build: ./api
    expose:
      - '80'
    ports:
      - '8000:80'
      - "8080:8080"
    depends_on:
      - db
    restart: always
    volumes:
      - ./api/app:/app
    command: /start-reload.sh
    env_file:
      - .env
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  # slack:
  #   build: ./slack
  #   env_file:
  #     - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8090:80
    volumes:
      - /sessions

volumes:
  db-store:


