on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        name: id_rsa # 省略可
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # 必須
    - name: run deploy script
      run: /usr/bin/ssh fusai@api.healthercise.k1h.dev "./deploy.sh"
